[build]
  command = "npm install && npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18.18.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["build/server/nodejs-eyJydW50aW1lIjoibm9kZWpzIn0/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"
